# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ringteam/ubuntu:cmake_opengl

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir build
          - cd build
          - cmake -DRINGMESH_WITH_GRAPHICS:BOOL=ON -DBUILD_RINGMESH_VIEW:BOOL=ON -DRINGMESH_TEST_GRAPHICS:BOOL=OFF -DRINGMESH_WITH_UTILITIES:BOOL=ON -DRINGMESH_WITH_TESTS:BOOL=ON -DRINGMESH_WITH_TUTORIALS:BOOL=ON ..
          - cd ringmesh/Release
          - make
          - make test
